<a href="https://colab.research.google.com/github/yunusbaskan213/yapayzeka/blob/main/numpy_2024_1074.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# 1) (10.,15,30,45,60) değerlerine sahip numpy dizisi oluştur


In [2]:
result=np.array([10,15,30,45,60])
result

array([10, 15, 30, 45, 60])

# 2 (5-15 arasındaki sayılarla bir dizi oluştur

In [3]:
result = np.arange(5,15)
result

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# 3) 50-100 arasında 5 er 5er artan bir dizi oluştur

In [5]:
result=np.arange(50,100,5)
result

array([50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

# 4) 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz

In [10]:
result = np.zeros(10)
result

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# 5) 10 elemanlı birilerden oluşan bir dizi oluşturunuz

In [11]:
result = np.ones(10)
result

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# 6) (0-100) arasında eşit aralıklı 5 sayı üretin

In [17]:
result = np.linspace(0,100,5)
result


array([  0.,  25.,  50.,  75., 100.])

# 7) (10-30) arasında rastgale 5 tane tamsayı üretin.



In [22]:
result=np.random.randint(10,30,5)
result

array([13, 24, 14, 14, 14])

# 8) (-1 ile 1) arasında 10 adet sayı üretin

In [23]:
result = np.random.randn(10)
result

array([-0.57329158, -0.63267676,  0.24328289,  1.68720593, -0.72509206,
       -0.29220204, -0.59934333, -0.30093585, -0.07910145, -0.1027546 ])

# 9) (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz

In [36]:
matris = np.random.randint(10,50,15).reshape(3,5)
matris

array([[19, 42, 42, 10, 36],
       [25, 12, 14, 40, 27],
       [24, 31, 21, 47, 17]])

# 11) Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?

In [37]:
result = matris.max()
result
result = matris.min()
result = matris.mean()
result

27.133333333333333

# 12) üretilen matrisin en büyük değerinin indeksi kaçtır

In [39]:
result = matris.argmax()
result = matris.argmin()
result

3

# 13) (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz

In [41]:
arr = np.arange(10,20)
print(arr)
result
result = arr[:3]

[10 11 12 13 14 15 16 17 18 19]


# 14) Üretilen dizinin elemanlarını tersten yazdırın

In [43]:
result = arr[::-1]
result

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

# 15) Üretilen matrisin ilk satırını seçiniz

In [44]:
result = matris [0]
result

array([19, 42, 42, 10, 36])

# 16) Üretilen matrisin 2.satır 3. sütundaki elemanı hangisidir

In [45]:
result = matris[1,2]
result

14

# 17) Üretilen matrisin tüm satırlarındaki ilk elemanı seçiniz

In [46]:
result = matris[:]
result

array([[19, 42, 42, 10, 36],
       [25, 12, 14, 40, 27],
       [24, 31, 21, 47, 17]])

# 18) Üretilen matrisin her bir elemanın karesini alınız

In [47]:
result = matris ** 2
result

array([[ 361, 1764, 1764,  100, 1296],
       [ 625,  144,  196, 1600,  729],
       [ 576,  961,  441, 2209,  289]])

# 19) Üretilen matris elemanlarının hangisi pozitif çift sayıdır ?
# Aralıgı (-50,+50) arasında yapınız.

In [48]:
result = matris % 2
print(result)

[[1 0 0 0 0]
 [1 0 0 0 1]
 [0 1 1 1 1]]
